name: Python application with artifact and repo commit

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Setting up runner
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Running model which outputs to a file in runner filesystem called "modelresult.txt"
    - name: Run the script
      run: |
        python model.py | tee modelresult.txt


    # Renaming of output file
    - name: Rename output file
      run: |
        TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
        FILENAME="modelresult_${TIMESTAMP}.txt"
        mv modelresult.txt ${FILENAME}

    # Upload of artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: "exported_${FILENAME}"
        path: ${FILENAME}

    # Commit of export file to repo
    - name: Commit files
      id: commit
      run: |
        git config --local user.email "wansengchin@gmail.com"
        git config --local user.name "JohnnyChin"
        git add --all
        if [[ -z "$(git status --porcelain)" ]]; then
          echo "::set-output name=push::false"
        else
          git commit -m "Export model result at timestamp ${TIMESTAMP}" -a
          echo "::set-output name=push::true"
        fi
      shell: bash

    # Push of export file to repo
    - name: Push changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}

    # Cleanup
    - name: Delete Artifact or Cleanup
      run: |
        if [[ -z "sample.txt" ]]; then
          rm sample.txt
        fi
